name: Build

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install protoc-gen plugin
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Install polyglot plugin for protoc-gen
        run: go install ./protoc-gen-rs-polyglot
      - name: Run generator
        run: protoc --rs-polyglot_out=privacy=public:./ examples/tests/tests.proto
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose
