name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install protoc-gen plugin
        working-directory: ./protoc-gen-polyglot-rs
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Install polyglot plugin for protoc-gen
        working-directory: ./protoc-gen-polyglot-rs
        run: go install protoc-gen-polyglot-rs/protoc-gen-polyglot-rs
      - name: Run generator
        working-directory: ./protoc-gen-polyglot-rs
        run: protoc --polyglot-rs_out=../ examples/test/test.proto
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features