name: Linting

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install protoc-gen plugin
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Install polyglot plugin for protoc-gen
        run: go install ./protoc-gen-rs-polyglot
      - name: Run generator
        run: protoc --rs-polyglot_out=privacy=public:../ examples/tests/tests.proto
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features