name: Tests

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - name: Install protoc-gen plugin
      working-directory: ./protoc-gen-rs-polyglot
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    - name: Install polyglot plugin for protoc-gen
      run: go install ./protoc-gen-rs-polyglot
    - name: Run generator
      run: protoc --rs-polyglot_out=./ examples/tests/tests.proto
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
